sakinawedsjuzar/Controllers/WeddingController.cs
using sakinawedsjuzar.Helper;
using sakinawedsjuzar.Models;
using sakinawedsjuzar.Models.AccountModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sakinawedsjuzar.Controllers
{
    public class WeddingController : Controller
    {
        //
        // GET: /Wedding/

        public ActionResult Index()
        {
            MasterModel model = new MasterModel();

            UserModel user = AuthHelper.LoginFromCookie();

            if (user != null)
            {
                model.isUserLoggedin = true;
            }
            model.loginModel = new Models.AccountModel.LoginModel();
            model.CommonInfo = Services.GetInstance.GetCommonInfo();
            model.MainSlideImages = Services.GetInstance.GetMainSliderImages();
            model.OurMemoriesPhotos = Services.GetInstance.GetImagesBySectionID(1);
            model.Bridesmaids = Services.GetInstance.GetImagesBySectionID(4);
            model.Groomsmens = Services.GetInstance.GetImagesBySectionID(5);
            model.lovestories = Services.GetInstance.GetLoveStories();
            model.events = Services.GetInstance.GetEvents();
            //model.comments = Services.GetInstance.GetComments();
            model.comments = Services.GetInstance.GetComments();
            return View(model);
        }

        public ActionResult LoveStories(MasterModel model)
        {

            return PartialView("~/Views/Shared/PartialLoveStoryTable.cshtml", model.lovestories);
        }
        public ActionResult Events(MasterModel model)
        {

            return PartialView("~/Views/Shared/PartialEventsTable.cshtml", model.events);
        }


        public ActionResult AddNewStory()
        {
            return PartialView("~/Views/Shared/PartialLoveStory.cshtml");
        }

        public ActionResult AddNewEvent()
        {
            return PartialView("~/Views/Shared/PartialEvents.cshtml");
        }

        public ActionResult AboutUsFooter()
        {
            CommonInfoModel model = Services.GetInstance.GetCommonInfo();
            return PartialView("~/Views/Shared/PartialAboutUS.cshtml", model);
        }

        public JsonResult UploadImageForCommonInfo(string imageData, string section)
        {
            string fileName = Guid.NewGuid().ToString();
            string url = "";
            string message = "";
            try
            {
                byte[] data = Convert.FromBase64String(imageData);
                System.IO.FileStream file = System.IO.File.Create(Server.MapPath("~/FileUpload/") + fileName + ".jpg");

                url = "/FileUpload/" + fileName + ".jpg";
                file.Write(data, 0, data.Length);
                file.Close();

                if (section == "6")
                {
                    EntityImage image = new EntityImage();

                    image.SectionID = 6;
                    image.Url = url;

                    Services.GetInstance.InsertEntityImage(image);
                }
                else if (section == "0couple")
                {
                    CommonInfo commonInfo = new CommonInfo();

                    commonInfo = Services.GetInstance.GetCommonInfoData();
                    commonInfo.CouplePictureUrl = url;

                    Services.GetInstance.UpdateCommonInfoData(commonInfo);

                }
                else if (section == "0gift")
                {
                    CommonInfo commonInfo = new CommonInfo();

                    commonInfo = Services.GetInstance.GetCommonInfoData();
                    commonInfo.GiftRegistryImageUrl = url;

                    Services.GetInstance.UpdateCommonInfoData(commonInfo);
                }
                else if (section == "1")
                {
                    EntityImage image = new EntityImage();

                    image.SectionID = 1;
                    image.Url = url;
                    image.thumbnail = url;

                    Services.GetInstance.InsertEntityImage(image);
                }

                else if (section == "4")
                {
                    EntityImage image = new EntityImage();

                    image.SectionID = 4;
                    image.thumbnail = url;

                    Services.GetInstance.InsertEntityImage(image);
                }
                else if (section == "5")
                {
                    EntityImage image = new EntityImage();

                    image.SectionID = 5;
                    image.thumbnail = url;

                    Services.GetInstance.InsertEntityImage(image);
                }

                message = "Image Uploaded Successfully!";
            }
            catch (Exception ex)
            {
                message = ex.Message.ToString();
            }

            return Json(new { Message = message }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UploadImageForLoveStory(string imageData)
        {
            string fileName = Guid.NewGuid().ToString();
            string url = "";
            string message = "";
            try
            {
                byte[] data = Convert.FromBase64String(imageData);
                System.IO.FileStream file = System.IO.File.Create(Server.MapPath("~/FileUpload/") + fileName + ".jpg");

                url = "/FileUpload/" + fileName + ".jpg";
                file.Write(data, 0, data.Length);
                file.Close();


            }
            catch (Exception ex)
            {
                message = ex.Message.ToString();
            }

            return Json(new { Message = message, ImageUrl = url }, JsonRequestBehavior.AllowGet);
        }
    }
}

sakinawedsjuzar/Views/Shared/PartialAboutUS.cshtml
@model sakinawedsjuzar.Models.CommonInfoModel
<div class="contact-inf">
    <h5 class="subtitle">About us</h5>
    @*<span class="couple_title">Sakina &amp; Juzar</span>*@
    <p class="description">
        @Model.AboutUs
    </p>
    @*<ul class="social-icons">
        <li><a title="Facebook" href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a title="Twitter" href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a title="Instagram" href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a title="Dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
        <li><a title="Tumblr" href="#"><i class="fa fa-tumblr"></i></a></li>
    </ul>*@
</div>

sakinawedsjuzar/Views/Shared/PartialEvents.cshtml
<div ng-controller="PostEventController">
    <h4 class="control-label">Post Event</h4>
    <form class="form-horizontal" role="form" ng-submit="submitEvent()">

        <h3 class="bg-success">{{message}}</h3>
        <h3 class="bg-danger" id="errMsg">{{errorName}}</h3>
            <div class="form-group">
                <label class="control-label col-sm-2" for="Title">Title:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="Title" id="Title" ng-model="Title" placeholder="Enter Title">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="EventLocation">Event Location:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="EventLocation" id="EventLocation" ng-model="EventLocation" placeholder="Enter One Word Location">
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="EventContent">Event Content:</label>
                <div class="col-sm-10">
                    <textarea class="form-control" name="EventContent" id="EventContent" ng-model="EventContent" placeholder="Enter Event Content"></textarea>
            
                </div>
            </div>

        <div class="form-group" id="data">
            <label class="control-label col-sm-2" for="myFile">Select Image</label>
            <div class="col-sm-10">
                <input type="file" name="file" id="fileEvents" file-model="file" class="form-control" multiple/>

            </div>

        </div>
        <output id="list-events"></output>
        <div class="form-group">
            <div class="col-sm-offset-10">
                <button type="submit" class="btn btn-default" id="submitEvent">Submit</button>
            </div>
        </div>
        <h3 class="bg-success">{{message}}</h3>
        <h3 class="bg-danger" id="errMsg">{{errorName}}</h3>
    </form>
</div>

<script type="text/javascript">
    $("#submitEvent").click(function () {
        var controllerElement = document.querySelector('[ng-controller="PostEventController"]');
        var controllerScope = angular.element(controllerElement).scope();
        
        var imgcollection = img.join(",");
        controllerScope.eventImageUrl = imgcollection;
    });
    function handleEvents(evt) {
        //console.log(evt);

        var files = evt.target.files; // FileList object

        // Loop through the FileList and render image files as thumbnails.
        for (var i = 0, f; f = files[i]; i++) {

            // Only process image files.
            if (!f.type.match('image.*')) {
                continue;
            }

            var reader = new FileReader();

            // Closure to capture the file information.
            reader.onload = (function (theFile) {
                return function (e) {
                    // Render thumbnail.
                    var ext = theFile.name.substring(theFile.name.lastIndexOf('.'));
                    var span = document.createElement('span');
                    if (ext == ".jpg") {
                        span.innerHTML = ['<br /><img class="img-responsive" src="', e.target.result,
                                          '" title="', escape(theFile.name), '"/><br /><br />'].join('');
                        span.innerHTML += ['<h5 class="alert alert-success">This file has been Uploaded Successfully!</h5>'].join('');
                    }
                    else {
                        span.innerHTML = ['<br /><br /><h4 class="alert alert-danger">This file cannot be uploaded as it is not in .jpg format</h4>'].join('');
                    }

                    dataUrlForEvent(e.target.result, ext);
                    document.getElementById('list-events').insertBefore(span, null);
                };
            })(f);

            // Read in the image file as a data URL.
            reader.readAsDataURL(f);
        }
        
    }
    var img = [];
    document.getElementById('fileEvents').addEventListener('change', handleEvents, false);
    function dataUrlForEvent(dataUrl, ext) {
        //console.log("dataUrl fetched" + dataUrl);

        if (ext == ".jpg") {
            dataUrl = dataUrl.replace('data:image/jpeg;base64,', '');
            $.ajax({
                type: 'POST',
                url: "/Wedding/UploadImageForLoveStory",
                data: '{ "imageData" : "' + dataUrl + '" }',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (data) {
                    //console.log(data.ImageUrl)
                    img.push(data.ImageUrl);
                    
                }
                
            });
            //img.join(",");
            //console.log(img);
           
        }
        else {
            $("#errMsg").html('Please select .jpg Image only!');
        }

    }
</script>

sakinawedsjuzar/Views/Shared/PartialEventsTable.cshtml
@model List<sakinawedsjuzar.Models.EventModel>


<input type="button" class="btn btn-default col-lg-3 col-xs-3" value="Add New" id="addEvent" />
<div id="AddEventForm" style="display:none">
    @Html.Partial("~/Views/Shared/PartialEvents.cshtml")

</div>

<br /><br /><br /><br />
<div class="container col-lg-12 col-xs-3">
    <h4 style="margin-top: -11px">J and S Events</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Event</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr ng-controller="DeleteEvent" id="@string.Format("{0}{1}", "tr", item.OurEventID)">
                    <td>@item.Title</td>
                    <td>@item.EventLocation</td>

                    <td>
                        @{
                            string content = "";

                            if (item.EventContent.Length > 100)
                            {
                                content = string.Format("{0}{1}{2}", item.EventContent.Substring(0, 30), " ", "...");
                            }
                            @content
                        }

                    </td>
                    <td><a ng-click="deleteThis('@item.OurEventID')" onclick="trClickfunction('@item.OurEventID')">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $("#addEvent").click(function () {
        $("#AddEventForm").css('display', 'block');
    });
</script>

sakinawedsjuzar/Views/Shared/PartialLogin.cshtml
@model sakinawedsjuzar.Models.AccountModel.LoginModel

@using (Html.BeginForm("Login", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h3 class="bg-success" role="alert" id="topMessage">{{message}}</h3>
    <h3 class="bg-danger" role="alert" id="errorLogin">{{errorName}}</h3>
    <div class="col-sm-6 col-lg-12">
        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-envelope fa-lg"></span>
            </span>
            <input type="text" class="form-control" placeholder="Enter Email" id="Username" name="Username">
        </div>

        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-asterisk fa-lg"></span>
            </span>
            <input type="text" class="form-control" placeholder="Enter Password" id="Password" name="Password">
        </div>
        <br />
        <input type="submit" class="btn btn-default" value="Submit" id="submitLogin" />
    </div>
}


<script type="text/javascript">
    $("#submitLogin").click(function () {
        if ($("#Username").val() != '' && $("#Password").val() != '') {

            $.ajax({
                url: "/Account/CheckUser",
                type: "GET",
                dataType: "html",
                data: { "username": $("#Username").val(), "password": $("#Password").val() },
                success: function (data) {
                    if (data == false) {
                        $("#errorLogin").html('Login Failed');
                        return false;
                    }

                }
                
            });
        }
        else {
            $("#errorLogin").html('The fields are Required fields');
            return false;
        }
    });
</script>

sakinawedsjuzar/Views/Shared/PartialLoveStory.cshtml
<div ng-controller="PostLoveStoryController">
    <h4 class="control-label">Post Story</h4>

    <form class="form-horizontal" role="form" ng-submit="uploadFile()">

        <h3 class="bg-success">{{message}}</h3>
        <h3 class="bg-danger" id="errMsg">{{errorName}}</h3>
        <div class="form-group">
            <label class="control-label col-sm-2" for="Title1">Title 1:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="Title1" id="Title1" placeholder="Enter Title 1" ng-model="Title1">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="Title2">Title 2:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="Title2" id="Title2" placeholder="Enter Title 2" ng-model="Title2">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="PublishDate">Publish Date:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="PublishDate" id="PublishDate" placeholder="Enter PublishDate (Apr 03, 2015)" ng-model="PublishDate">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="Content">Content</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="Content" id="Content" placeholder="Enter Content" ng-model="Content">
            
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="CommentBy">CommentBy</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="CommentBy" id="CommentBy" placeholder="Enter CommentBy" ng-model="CommentBy">
            
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="SpecialComment">Special Comment</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="SpecialComment" id="SpecialComment" placeholder="Enter Special Comment" ng-model="SpecialComment">

            </div>
        </div>
        
        <div class="form-group" id="data">
            <label class="control-label col-sm-2" for="myFile">Select Image</label>
            <div class="col-sm-10">
                <input type="file" name="file" id="fileLoveStory" file-model="file" class="form-control" />
                
            </div>
           
        </div>
        <output id="list-LoveStory"></output>
        <div  id="demo"></div>
         @*<div class="form-group">
            <div class="col-sm-10">
                <label class="control-label col-sm-2" for="myFile">Select Template</label>
                <div class="col-sm-10">
                    <select id="TemplateId" name="TemplateId" ng-model="TemplateId" class="form-control">
                        <option value="1">Right Template Style</option>
                        <option value="2">Left Template Style</option>
                    </select>
                </div>
                </div>

        </div>*@
        <div class="form-group ">
            <label class="control-label col-sm-2" for="select">
                Select a Choice
            </label>
            <div class="col-sm-10">
                <select class="select form-control" id="TemplateId" name="TemplateId" ng-model="TemplateId">
                    <option value="1">Right Template Style</option>
                    <option value="2">Left Template Style</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-10">
                <button type="submit" class="btn btn-default" ng-click="submit()">Submit</button>
            </div>
        </div>
        <h3 class="bg-success">{{message}}</h3>
        <h3 class="bg-danger">{{errorName}}</h3>
    </form>
</div>


<script type="text/javascript">
    function handleLoveStory(evt) {
        //console.log(evt);
        
        var files = evt.target.files; // FileList object

        // Loop through the FileList and render image files as thumbnails.
        for (var i = 0, f; f = files[i]; i++) {

            // Only process image files.
            if (!f.type.match('image.*')) {
                continue;
            }

            var reader = new FileReader();

            // Closure to capture the file information.
            reader.onload = (function (theFile) {
                return function (e) {
                    // Render thumbnail.
                    var ext = theFile.name.substring(theFile.name.lastIndexOf('.'));
                    var span = document.createElement('span');
                    if (ext == ".jpg") {
                        span.innerHTML = ['<br /><img class="img-responsive" src="', e.target.result,
                                          '" title="', escape(theFile.name), '"/><br /><br />'].join('');
                        span.innerHTML += ['<h5 class="alert alert-success">This file has been Uploaded Successfully!</h5>'].join('');
                    }
                    else {
                        span.innerHTML = ['<br /><br /><h4 class="alert alert-danger">This file cannot be uploaded as it is not in .jpg format</h4>'].join('');
                    }

                    dataUrlForStory(e.target.result, ext, "0lovestory");
                    document.getElementById('list-LoveStory').insertBefore(span, null);
                };
            })(f);

            // Read in the image file as a data URL.
            reader.readAsDataURL(f);
        }
    }
    document.getElementById('fileLoveStory').addEventListener('change', handleLoveStory, false);
    function dataUrlForStory(dataUrl, ext, section) {
        //console.log("dataUrl fetched" + dataUrl);

        if (ext == ".jpg") {
            dataUrl = dataUrl.replace('data:image/jpeg;base64,', '');
            $.ajax({
                type: 'POST',
                url: "/Wedding/UploadImageForLoveStory",
                data: '{ "imageData" : "' + dataUrl + '" }',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (data) {
                    var controllerElement = document.querySelector('[ng-controller="PostLoveStoryController"]');
                    var controllerScope = angular.element(controllerElement).scope();
                    controllerScope.ImageUrl = data.ImageUrl;
                   
                }
            });
        }
        else {
            $("#errMsg").html('Please select .jpg Image only!');
        }

    }
</script>

sakinawedsjuzar/Views/Shared/PartialLoveStoryTable.cshtml
@model List<sakinawedsjuzar.Models.LoveStoryModel>


<input type="button" class="btn btn-default col-lg-3 col-xs-3" value="Add New" id="addStory" />
<div id="AddNewForm" style="display:none">
    @Html.Partial("~/Views/Shared/PartialLoveStory.cshtml")
</div>

<br /><br /><br /><br />
<div class="container col-lg-12 col-xs-3">
  <h4 style="margin-top:-11px">Stories</h4>
  <table class="table">
    <thead>
      <tr>
        <th>Story Name</th>
        <th>Publish Date</th>
        <th>CommentBy</th>
      </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
      <tr ng-controller="DeleteLovStory" id="@string.Format("{0}{1}", "tr", item.OurStoryID)">
        <td>@string.Format("{0}{1}{2}", item.Title1, " ", item.Title2)</td>
        <td>@item.PublishDate</td>
       
          <td>@item.CommentBy</td>
          <td><a ng-click="deleteThis('@item.OurStoryID')" onclick="trClickfunction('@item.OurStoryID')">Delete</a></td>

      </tr>

        }
    </tbody>
  </table>
</div>

<script type="text/javascript">

    function trClickfunction(val) {

        $('#tr' + val).html('');
        //alert("tr" + val);
    }
    $("#addStory").click(function () {
        //$.ajax({
        //    url: "/Wedding/AddNewStory",
        //    type: "GET",
        //    dataType: "html",
        //    success: function (data) {
        //        $("#AddNewForm").html(data);
        //    }
        //});
        $("#AddNewForm").css('display', 'block');
    });
</script>

sakinawedsjuzar/Views/Shared/PartialRegister.cshtml
<form class="form-horizontal" role="form">
    <h3 class="bg-success" role="alert" id="topMessage">{{message}}</h3>
    <h3 class="bg-danger" role="alert">{{errorName}}</h3>
    <div class="col-sm-6 col-lg-12">
        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-envelope fa-lg"></span>
            </span>
            <input type="text" class="form-control" placeholder="Enter Email">
        </div>

        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-asterisk fa-lg"></span>
            </span>
            <input type="text" class="form-control" placeholder="Enter Password">
        </div>

        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-user fa-lg"></span>
            </span>
            <input type="text" class="form-control" placeholder="Enter FullName">
        </div>

        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-camera fa-lg"></span>
            </span>
            <input type="file" class="form-control btn btn-default">
        </div>
        <br />
        <input type="submit" class="btn btn-default" value="Submit" />
    </div>
</form>

sakinawedsjuzar/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script src="~/scripts/angular.min.js"></script>
    <script src="~/scripts/WeddingApp.js"></script>
    <script src="~/scripts/jquery-1.7.1.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <![endif]-->
    
    <!--[if IE 9]>
    <link rel="stylesheet" type="text/css" href="css/ie9.css" />
    <![endif]-->
        
    <!-- Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Favicons Icon -->
    <link rel="icon" href="../../images/couple.png" type="image/x-icon" style="width:25px;height:25px;" />
	
    <title>Sakina-Weds-Juzar!</title>
    
    <!-- CSS Styles -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
    <link rel="stylesheet" type="text/css" href="css/animate.css" />
    <link rel="stylesheet" type="text/css" href="css/rotating.css" />
    <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" />
    <link rel="stylesheet" type="text/css" href="css/swipebox.css" />
    <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" />
    <link rel="stylesheet" type="text/css" href="css/owl.theme.css" />
    <link rel="stylesheet" type="text/css" href="css/jcf.css" />
    <link rel="stylesheet" type="text/css" href="css/slider.css" />
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    
    <!-- Google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Maven+Pro:400,700' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700|Open+Sans:300,400,700|Abel' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css' />   
    <link href="http://fonts.googleapis.com/css?family=Engagement" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800' rel='stylesheet' type='text/css' />

    <link href="~/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet" />
</head>

<body class="cms_index" ng-app="MyModule">
    <!-- content_wrapper start -->
	@RenderBody()
    <!-- content_wrapper End -->
    
    <!-- Footer Start-->

    @if (!Request.Url.ToString().ToLower().Contains("apihelper"))
    {
    <footer>
        <div class="container">
            <div class="row">            
                <div class="col-md-12">            
                    <img src="images/couple.png" alt="Couple Icon" class="img-responsive" data-scroll-reveal="enter top move 35px, after 0.4s" />          
                    <div class="col-lg-4 col-md-5" data-scroll-reveal="enter left move 35px, after 0.4s">
                         @Html.Partial("~/Views/Shared/ContactUsPartial.cshtml")
                                                
                    </div>

                    <div class="col-lg-4 col-md-5 pull-right" data-scroll-reveal="enter right move 35px, after 0.4s">
                    	@{Html.RenderAction("AboutUsFooter", "Wedding"); }
                       
                    </div>
                </div>
            </div>
        </div>
        <div class="row mr_none">
            <p class="copyright" data-scroll-reveal="enter top move 5px, after 0.1s">&copy; 2016. All Rights Reserved. Designed by <a href="#" target="_blank">Juzar Noorani</a></p>
        </div>
    </footer>
    }
    <!-- End Footer -->    
    
    <!-- JavaScript -->
	<script type="text/javascript" src="js/modernizr-2.8.3-respond-1.4.2.min.js"></script>
	<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/jcf.js"></script>
    <script type="text/javascript" src="js/jcf_select.js"></script>
    <script type="text/javascript" src="js/modernizr.custom.js"></script>
    <script type="text/javascript" src="js/jquery.swipebox.js"></script>
    <script type="text/javascript" src="js/smooth-scroll.js"></script>    
    <script type="text/javascript" src="js/wow.min.js"></script>
    <script type="text/javascript" src="js/scrollReveal.js"></script>
    <script type="text/javascript" src="js/jquery.backstretch.js"></script>
    <script type="text/javascript" src="js/jquery.simple-text-rotator.js"></script>
    <script type="text/javascript" src="js/jquery.magnific-popup.js"></script>
    <script type="text/javascript" src="js/jquery.lettering.js"></script>
    <script type="text/javascript" src="js/jquery.firefly-0.3.js"></script>
	<script type="text/javascript" src="js/jquery.placeholder.js"></script>
	<script type="text/javascript" src="js/along.js"></script>
	<script type="text/javascript" src="js/jquery-plugin-collection.js"></script>
    <script type="text/javascript" src="js/owl.carousel.js"></script>
    
    <script type="text/javascript" src="js/minpace.js"></script>
    <script type="text/javascript" src="js/jquery.flexslider.js"></script>
    <script type="text/javascript" src="js/jquery.points.min.js"></script>
    <script type="text/javascript" src="js/slidermin.min.js"></script>
    <script type="text/javascript" src="js/main-slider-fade.js"></script>
    
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="js/js-functions.js"></script>
	<script type="text/javascript" src="js/cross-browser.js"></script>
        
</body>
</html>
<script type="text/javascript">
   
    function Logout() {
        window.location = '/Account/Logout';
    }
</script>